
services:
  indexer:
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./config:/app/config
    networks:
      - anetav2_backend
    restart: always

networks:
  anetav2_backend:
    external: true